<template>
	<div id="app">
		<gh-btns-watch
			slug="vuejs/vue"
			show-count
		/>
		<gh-btns-star
			slug="vuejs/vue"
			show-count
			reverse
		></gh-btns-star>
		<gh-btns-star
			slug="vuejs/vue"
			show-count
			icon="mark-github"
			reverse>
		</gh-btns-star>
		<gh-btns-fork
			slug="vuejs/vue"
			show-count
		/>
		<gh-btns-follow
			user="yyx990803"
			show-count
		/>
	</div>
</template>
